from app.schemas.auth import (
    AuthResponse,
    LoginRequest,
    SignupRequest,
    UserProfileResponse,
    UserRead,
    UserUpdateRequest,
)
from app.schemas.coaching import CoachingResponse
from app.schemas.leaderboard import (
    LeaderboardItem,
    LeaderboardResponse,
    LeaderboardUpdateRequest,
    LeaderboardUpdateResponse,
)
from app.schemas.shop import PurchaseRequest, PurchaseResponse, ShopItemsResponse
from app.schemas.stats import StatsResponse
from app.schemas.tutorial import (
    TutorialCompleteRequest,
    TutorialCompleteResponse,
    TutorialDetail,
    TutorialDetailResponse,
    TutorialListItem,
    TutorialListResponse,
    UserProgressItem,
    UserProgressResponse,
)
from app.schemas.video import (
    PoseCorrectionCreateRequest,
    PoseCorrectionResponse,
    RoundResultCreateRequest,
    RoundResultResponse,
    SessionCreateRequest,
    SessionCreateResponse,
    SessionEndRequest,
    SessionEndResponse,
    VideoDetail,
    VideoDetailResponse,
    VideoListItem,
    VideoListResponse,
)

__all__ = [
    "SignupRequest",
    "LoginRequest",
    "AuthResponse",
    "UserRead",
    "UserProfileResponse",
    "UserUpdateRequest",
    "TutorialListItem",
    "TutorialDetail",
    "TutorialListResponse",
    "TutorialDetailResponse",
    "TutorialCompleteRequest",
    "TutorialCompleteResponse",
    "UserProgressItem",
    "UserProgressResponse",
    "VideoListItem",
    "VideoListResponse",
    "VideoDetail",
    "VideoDetailResponse",
    "SessionCreateRequest",
    "SessionCreateResponse",
    "SessionEndRequest",
    "SessionEndResponse",
    "RoundResultCreateRequest",
    "RoundResultResponse",
    "PoseCorrectionCreateRequest",
    "PoseCorrectionResponse",
    "StatsResponse",
    "LeaderboardItem",
    "LeaderboardResponse",
    "LeaderboardUpdateRequest",
    "LeaderboardUpdateResponse",
    "CoachingResponse",
    "ShopItemsResponse",
    "PurchaseRequest",
    "PurchaseResponse",
]
